spring:
  application:
    name: springbatch
  #  batch:
  #    job:
  #      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.ddl-auto: create
      hibernate.show-sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.format_sql: true
      logging.level.org.hibernate.type.descriptor.sql: trace
