rootProject.name = "TIL"
include("transaction")
include("concurrency")
include("springbatch")
include("multithread")
include("concurrency_practice")
include("concurrency_practice_consumer")
include("concurrency_coroutine")
include("concurrency_redisson")
include("spring_db")
include("spring_db_practice")
include("kafka")
include("study")
include("webclient")
include("springsecurity")

