rootProject.name = "msa_architecture_service"
include("order_service")
include("order_service:order-application")
include("order_service:order-container")
include("order_service:order-data-access")
include("order_service:order-domain")
include("order_service:order-domain:order-domain-core")
include("order_service:order-domain:order-application-service")
include("order_service:order-messaging")
include("common:common-application")
include("common:common-data-access")
include("common:common-domain")