{{- if .Values.components.k6 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-proto
  namespace: {{ .Release.Namespace }}
data:
{{- range $path, $_ := .Files.Glob "protos/*.proto" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}