name: Kotlin Code Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Kover
#        run: ./gradlew koverReport
        run: ./gradlew koverHtmlReport

#      - name: Upload Coverage to CodeCov
#        uses: codecov/codecov-action@v2
#        with:
#          files: ./build/reports/kover/xmlReport.xml
#          fail_ci_if_error: true