name: maven publish Github packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and Publish
        run: |
          ./gradlew publish

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_USER_ID: ${{ secrets.PERSONAL_USER_ID }}
          PERSONAL_USER_KEY: ${{ secrets.PERSONAL_USER_KEY }}